---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: "{{ monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install Prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ monitoring_namespace }}"
    values:
      grafana:
        enabled: true
        adminPassword: admin123
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.wasaachat.com
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
      prometheus:
        prometheusSpec:
          retention: 30d
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: gp3
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 50Gi
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - prometheus.wasaachat.com
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /

- name: Create monitoring ingress
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: monitoring-ingress
        namespace: "{{ monitoring_namespace }}"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        rules:
        - host: grafana.wasaachat.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: prometheus-grafana
                  port:
                    number: 80
        - host: prometheus.wasaachat.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: prometheus-kube-prometheus-prometheus
                  port:
                    number: 9090