# ArgoCD Project for WASAA Supporting Infrastructure
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wasaa-supporting
  namespace: argocd
  labels:
    project-type: infrastructure
spec:
  description: "WASAA Platform Supporting Infrastructure (Ingress, Cert-Manager, Load Balancers, Autoscalers)"
  
  sourceRepos:
    - 'https://github.com/web-masters-ke/wasaa-infra.git'
    - 'https://github.com/Ayugi2023/wasaa-eks-infra.git'
    - 'https://github.com/webmasters-Team/wasaa-infra.git'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/autoscaler'
    - 'https://aws.github.io/eks-charts'
    - 'https://charts.bitnami.com/bitnami'
  
  destinations:
    - namespace: 'ingress-nginx'
      server: https://kubernetes.default.svc
    - namespace: 'cert-manager'
      server: https://kubernetes.default.svc
    - namespace: 'kube-system'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
    - namespace: 'jobs'
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    # cert-manager is no longer used; ClusterIssuer is not required in this project.
    - group: networking.k8s.io
      kind: IngressClass
  
  namespaceResourceWhitelist:
    - group: ''
      kind: Secret
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: DaemonSet
    - group: ''
      kind: PersistentVolumeClaim
    - group: networking.k8s.io
      kind: Ingress
    - group: ''
      kind: Pod
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    # cert-manager Certificate/Issuer kinds removed; TLS is terminated at ALB with ACM.
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: policy
      kind: PodDisruptionBudget
    - group: argoproj.io
      kind: Application
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  
  roles:
    - name: infrastructure-admin
      description: Full access to supporting infrastructure
      policies:
        - p, proj:wasaa-supporting:infrastructure-admin, applications, *, wasaa-supporting/*, allow
        - p, proj:wasaa-supporting:infrastructure-admin, repositories, *, *, allow
      groups:
        - wasaa:platform-team
        - wasaa:devops-team
    
    - name: infrastructure-operator
      description: Operational access to infrastructure
      policies:
        - p, proj:wasaa-supporting:infrastructure-operator, applications, get, wasaa-supporting/*, allow
        - p, proj:wasaa-supporting:infrastructure-operator, applications, sync, wasaa-supporting/*, allow
        - p, proj:wasaa-supporting:infrastructure-operator, applications, delete, wasaa-supporting/*, deny
      groups:
        - wasaa:sre-team
    
    - name: infrastructure-readonly
      description: Read-only access to infrastructure
      policies:
        - p, proj:wasaa-supporting:infrastructure-readonly, applications, get, wasaa-supporting/*, allow
        - p, proj:wasaa-supporting:infrastructure-readonly, applications, sync, wasaa-supporting/*, deny
      groups:
        - wasaa:developers
