replicaCount: 2


hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 65

resources:
  requests:
    cpu: 150m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 768Mi


# Override helm charts ECR registry with correct account ID
image:

# Externalized environment via secret (created separately)
envFrom:
  - secretRef:
      name: wasaa-web-service-env

# Ensure serviceAccount is not creating new ones
serviceAccount:
  create: false
  name: default

# Disable ingress - managed by Helm chart
ingress:
  enabled: false
