replicaCount: 3

# Override helm charts ECR registry with correct account ID


hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 65

resources:
  requests:
    cpu: 150m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 768Mi


# Database connection environment variables


# Ensure serviceAccount is not creating new ones
serviceAccount:
  create: false
  name: default
