replicaCount: 2

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: test.calls-api.wasaachat.com
      paths:
        - path: /
          pathType: Prefix

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

    value: "6379"

serviceAccount:
  create: false
  name: default
