replicaCount: 3


hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 600m
    memory: 1Gi


# Health probe configuration - ensure ports are set to 8083
livenessProbe:
  httpGet:
    path: /health
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8083
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Ensure serviceAccount is not creating new ones
serviceAccount:
  create: false
  name: default

# Persistence configuration (disabled by default). Enable if the gateway needs PVC-backed storage.
persistence:
  enabled: false
  storageClass: gp3
  size: 5Gi
  accessModes:
    - ReadWriteOnce

# Disable ingress - managed by Helm chart
ingress:
  enabled: false
