replicaCount: 2


# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 65

# Resource requests and limits
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi




# Ensure serviceAccount is not creating new ones
serviceAccount:
  create: false
  name: default

# Disable ingress - managed by Helm chart
ingress:
  enabled: false
