all:
  children:
    eks_cluster:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        cluster_name: wasaa-prod-eks
        aws_region: af-south-1
        environment: prod