# Production Environment Root Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wasaa-production-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: wasaa-platform
    app.kubernetes.io/part-of: wasaa-root
    app.kubernetes.io/managed-by: argocd
    environment: production
spec:
  project: wasaa-applications
  source:
    repoURL: https://github.com/Ayugi2023/wasaa-eks-infra.git
    targetRevision: main
    path: argocd/app-of-apps
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10