# ArgoCD Application for Loki
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: wasaa-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wasaa-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.47.0 # Example version; adjust as needed
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClassName: gp3  # AWS: gp3, Local: standard (minikube-hostpath)
            size: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          service:
            type: NodePort
            nodePort: 31000
        gateway:
          enabled: false
        test:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
          lokiCanary:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
  info:
    - name: 'Purpose'
      value: 'Log aggregation system with MinIO/S3 storage'
    - name: 'Owner'
      value: 'WASAA Observability Team'