# ArgoCD Application for Pyroscope
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  labels:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/part-of: wasaa-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wasaa-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: pyroscope
    targetRevision: 1.1.0 # example version; adjust as needed
    helm:
      values: |
        pyroscope:
          persistence:
            enabled: true
            storageClassName: gp3  # AWS: gp3, Local: standard (minikube-hostpath)
            size: 5Gi
          replicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/rewrite-target: /
            hosts:
              - dev-pyroscope.wasaachat.com
            tls:
              - secretName: pyroscope-tls
                hosts:
                  - dev-pyroscope.wasaachat.com
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3