# Root ArgoCD Application for WASAA Microservices
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wasaa-microservices
  namespace: argocd
spec:
  project: wasaa-microservices
  source:
    repoURL: https://github.com/Ayugi2023/wasaa-eks-infra.git
    targetRevision: main
    path: argocd/applications/wasaa-microservices
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 5
  info:
    - name: 'Description'
      value: 'WASAA microservices: all business applications'
    - name: 'Deploy Order'
      value: 'All microservices deployed in parallel'
