# wasaa-apps-service-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wasaa-apps-service-developer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wasaa-microservices
  sources:
    - repoURL: https://github.com/web-masters-ke/wasaa-chat-helm-charts.git
      targetRevision: main
      path: wasaa-apps-service
      helm:
        releaseName: wasaa-apps-service
    - repoURL: https://github.com/Ayugi2023/wasaa-eks-infra.git
      targetRevision: main
      path: argocd/environments/production
      helm:
        valueFiles:
          - wasaa-apps-service-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wasaa-apps-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data
