# wasaa-message-service-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wasaa-message-service-developer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wasaa-microservices
  sources:
    - repoURL: https://github.com/web-masters-ke/wasaa-chat-helm-charts.git
      targetRevision: main
      path: wasaa-message-service
      helm:
        releaseName: wasaa-message-service
        values: |-
          replicaCount: 2
          
          hpa:
            enabled: true
            minReplicas: 1
            maxReplicas: 10
            targetCPUUtilizationPercentage: 70
          
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          
          serviceAccount:
            create: false
            name: default
          
          env:
            PORT: "3005"
            MONGODB_SSL_CA_FILE: "/etc/ssl/certs/mongodb/global-bundle.pem"
            MONGODB_TLS: "true"
          
          volumes:
            - name: docdb-ssl-cert
              configMap:
                name: docdb-ssl-cert
          
          volumeMounts:
            - name: docdb-ssl-cert
              mountPath: /etc/ssl/certs/mongodb
              readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: wasaa-message-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data