---
- name: Check if security namespace exists
  shell: kubectl get namespace security-system
  register: security_ns_exists
  ignore_errors: yes
  changed_when: false

- name: Check if pod-reader ClusterRole exists
  shell: kubectl get clusterrole pod-reader
  register: pod_reader_exists
  ignore_errors: yes
  changed_when: false

- name: Apply basic security policies
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Namespace
    metadata:
      name: security-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: pod-reader
    rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "watch", "list"]
    EOF
  when: security_ns_exists.rc != 0 or pod_reader_exists.rc != 0

- name: Display security information
  debug:
    msg: "Basic security policies applied. Pod Security Standards are enforced at the cluster level."