---
- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    name: "{{ argocd_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: "{{ argocd_namespace }}"
    values:
      server:
        service:
          type: ClusterIP
        extraArgs:
          - --insecure
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - argocd.wasaachat.com
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTP
            nginx.ingress.kubernetes.io/rewrite-target: /
      configs:
        repositories:
          - url: https://github.com/web-masters-ke/wasaa-chat-helm-charts.git
            type: git
          - url: https://helm.releases.hashicorp.com
            type: helm
            name: hashicorp
          - url: https://kubernetes-sigs.github.io/aws-load-balancer-controller
            type: helm
            name: aws-load-balancer-controller

- name: Wait for ArgoCD server to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: argocd-server
    namespace: "{{ argocd_namespace }}"
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300

- name: Create ArgoCD ingress
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: argocd-ingress
        namespace: "{{ argocd_namespace }}"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        rules:
        - host: argocd.wasaachat.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: argocd-server
                  port:
                    number: 80