apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: microservices
spec:
  template:
    metadata:
      labels:
        nodegroup-type: microservices
        workload: microservices
    spec:
      nodeClassRef:
        name: microservices
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3.large", "t3.xlarge", "t3a.medium", "t3a.large", "t3a.xlarge", "m5.large", "m5.xlarge", "m5a.large", "m5a.xlarge"]
      taints:
        - key: workload
          value: microservices
          effect: NoSchedule
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s